/**
 * Peerkith reference verifier — single file, zero deps (Node 20+ / browsers / Workers).
 * broker v1-week1.2
 * GENERATED by scripts/build-ref-verify.mjs from (do not edit; rebuild):
 *   functions/_lib/identity.js sha256=20fd504973ef5bb7ffa00ccde25d21ead91f52a2b251cdf93dc955d9276e4fe7
 *   functions/_lib/proof-broker.js sha256=c8767ec257456f4fa0a5c008aee7f0f2ad775e2eada15401f699e7e17349cdf6
 *   functions/_lib/tier.js sha256=84ee1bb7ea18d0673dfc3d683719d8aa8ec91d479f7c0f86177c433c713b27e4
 *
 * CLI:
 *   node verify.js --card '<card>' --job '<job>' --proof '<proof>'
 *   node verify.js --row row.json            (five-field row JSON file or inline JSON)
 *   node verify.js --row row.json --offline artifact.bin
 *     --offline: every proof fetch is served from this local file (no network).
 *     Use for sha256:<hex> https://… or JSON receipts you saved yourself.
 * Prints the same JSON as GET/POST https://peerkith.com/verify:
 *   {ok, tier, reason, verified_by, checked_at, broker, row?}. Exit 0 = verified.
 * Library: require("./verify.js").checkRow({card, job, proof}) → Promise<verdict>.
 */
(function () {
"use strict";
let pkFetch = (...a) => globalThis.fetch(...a);

// ---- identity.js ----
/**
 * Required ed25519 signed card + sig addon for verified wall (Week 1).
 * card form: DisplayName|ed25519:<base64url-32-byte-pubkey>
 * proof addon: sig:ed25519:<base64url-sig> (alone or after a trusted proof)
 * message: UTF-8 card.trim() + "\n" + job.trim()
 * Sig is an addon check — not a proof type id. No wallet / DID/VC.
 */

/** DisplayName|ed25519:<43-char base64url of 32-byte pubkey> (no pad). */
const SIGNED_CARD_RE =
  /^(.+)\|ed25519:([A-Za-z0-9_-]{43})$/;

/** Trailing or lone sig addon — stripped before proof-broker classify. */
const SIG_ADDON_RE = /(?:^|\s)sig:ed25519:([A-Za-z0-9_-]{86})(?:\s*)$/i;

function b64urlToBytes(s) {
  const pad = "=".repeat((4 - (s.length % 4)) % 4);
  const b64 = (s + pad).replace(/-/g, "+").replace(/_/g, "/");
  const bin = atob(b64);
  const out = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) out[i] = bin.charCodeAt(i);
  return out;
}

function bytesToB64url(bytes) {
  let bin = "";
  for (let i = 0; i < bytes.length; i++) bin += String.fromCharCode(bytes[i]);
  return btoa(bin).replace(/\+/g, "-").replace(/\//g, "_").replace(/=+$/, "");
}

/**
 * @returns {{ signed: false } | { signed: true, display: string, pubkey: string }}
 */
function parseSignedCard(card) {
  if (typeof card !== "string" || !card.trim()) {
    return { signed: false };
  }
  const m = card.trim().match(SIGNED_CARD_RE);
  if (!m) return { signed: false };
  const display = m[1];
  const pubkey = m[2];
  if (!display || !display.trim()) return { signed: false };
  try {
    const raw = b64urlToBytes(pubkey);
    if (raw.length !== 32) return { signed: false };
  } catch {
    return { signed: false };
  }
  return { signed: true, display: display.trim(), pubkey };
}

/**
 * Strip sig:ed25519 addon from proof string. Sig is an addon check, not a type id.
 * @returns {{ proof: string, sig: string|null }}
 */
function stripSigAddon(proof) {
  if (typeof proof !== "string") return { proof: "", sig: null };
  const p = proof.trim();
  const m = p.match(SIG_ADDON_RE);
  if (!m) return { proof: p, sig: null };
  const sig = m[1];
  const without = p.replace(SIG_ADDON_RE, "").trim();
  return { proof: without, sig };
}

/** Canonical message for ed25519 verify. */
function identityMessage(card, job) {
  const c = typeof card === "string" ? card.trim() : "";
  const j = typeof job === "string" ? job.trim() : "";
  return `${c}\n${j}`;
}

/**
 * Verify ed25519 signature over UTF-8 message with raw 32-byte pubkey (base64url).
 * @returns {Promise<boolean>}
 */
async function verifyEd25519Sig(pubkeyB64url, message, sigB64url) {
  if (
    typeof pubkeyB64url !== "string" ||
    typeof message !== "string" ||
    typeof sigB64url !== "string"
  ) {
    return false;
  }
  let pubBytes;
  let sigBytes;
  try {
    pubBytes = b64urlToBytes(pubkeyB64url);
    sigBytes = b64urlToBytes(sigB64url);
  } catch {
    return false;
  }
  if (pubBytes.length !== 32 || sigBytes.length !== 64) return false;

  try {
    const key = await crypto.subtle.importKey(
      "raw",
      pubBytes,
      { name: "Ed25519" },
      false,
      ["verify"]
    );
    const msg = new TextEncoder().encode(message);
    return await crypto.subtle.verify({ name: "Ed25519" }, key, sigBytes, msg);
  } catch {
    return false;
  }
}

/**
 * Decide promote identity gate after proof broker ok.
 * Week 1: verified wall REQUIRES signed card + valid sig.
 * Plain nickname → never promote (even if proof allowlist passes).
 * @returns {Promise<{ promote: boolean, identity: "signed"|null, detail: string }>}
 */
async function checkIdentityForPromote(card, job, proofRaw) {
  const cardInfo = parseSignedCard(card);
  const { sig } = stripSigAddon(proofRaw || "");

  if (!cardInfo.signed) {
    return {
      promote: false,
      identity: null,
      detail: "plain card; verified wall requires signed card + sig (Week 1)",
    };
  }

  if (!sig) {
    return {
      promote: false,
      identity: null,
      detail: "signed card requires sig:ed25519 addon for verified wall",
    };
  }

  const msg = identityMessage(card, job);
  const ok = await verifyEd25519Sig(cardInfo.pubkey, msg, sig);
  if (!ok) {
    return {
      promote: false,
      identity: null,
      detail: "ed25519 signature invalid",
    };
  }

  return {
    promote: true,
    identity: "signed",
    detail: "ed25519 signature valid",
  };
}

// ---- proof-broker.js ----
/**
 * Proof broker v1 (Week 1) — verified allowlist only. Version: BROKER_VERSION.
 * Type is prefix/pattern, never a sixth wall field.
 * Promote-capable: sha256(+URL) | https-text (JSON receipt+off-origin) | git-commit | ci.
 * peerkith retained as classify label only — never ok:true.
 * Bare job-hash / bare GET 200 / HTML → always pending.
 * world:true only for verified off-origin https fetches.
 */

const PROOF_TYPES = {
  sha256:
    "sha256:<64 hex> https://… — fetched body hash must match; prefer off-origin (world:true). Bare job-hash alone → pending (never verify).",
  "https-text":
    "https:// off-origin URL; GET 200; application/json with body.job === job (Proof Bind receipt). Plain text/HTML/same-origin → pending.",
  "git-commit":
    "https://github|gitlab|…/commit/<40hex> (or /commits/<sha>); GET 200 + page/API shows that SHA; soft-404 → pending.",
  ci:
    "https://… GitHub Actions run / check-runs style URL; GET 200 + success signal in JSON/HTML; ambiguous → pending.",
  peerkith:
    "https://peerkith.com/… — classify only; same-origin always pending (never promote).",
};

/** One version string: broker, /verify responses, /ref/verify.js. */
const BROKER_VERSION = "v1-week1.2";

/**
 * ONE owned-host constant (TL addendum #4). Shared by tier.js, /spec.json
 * (scripts/build-ref-verify.mjs writes it there) and /ref/verify.js (bundled).
 * Match: host === entry OR host ends with "." + entry. Shared-suffix platforms
 * are listed by exact project host (their own preview subdomains match);
 * a bare public suffix such as "pages.dev" is never allowed.
 */
const OWNED_HOSTS = [
  "peerkith.com",
  "knockorno.com",
  "peerkith-base.pages.dev",
  "mass-ledger-pages.pages.dev",
];
const TOO_BROAD = new Set(["pages.dev", "workers.dev", "github.io", "netlify.app", "vercel.app"]);
for (const h of OWNED_HOSTS) {
  if (TOO_BROAD.has(h) || h.split(".").length < 2) throw new Error(`OWNED_HOSTS entry too broad: ${h}`);
}

function isOwnedHost(hostname) {
  const h = String(hostname || "").toLowerCase().replace(/\.$/, "");
  if (!h) return false;
  return OWNED_HOSTS.some((o) => h === o || h.endsWith("." + o));
}

/**
 * JOB-BOUND (QA 2026-09-28): (a) JSON receipt with body.job === job, or
 * (b) the exact job text appears inside the fetched artifact.
 * FE guard on (b): job must be >= JOB_TEXT_MIN chars so tiny jobs ("fix")
 * cannot bind to any document. Anything else → not job-bound.
 */
const JOB_TEXT_MIN = 16;

const UA = { "User-Agent": "peerkith-proof-check/2.1" };

/** Fetch limits (TL ACK #3): https only, timeout, byte cap, no non-https redirect. */
const FETCH_TIMEOUT_MS = 5000;
const FETCH_MAX_BYTES = 1048576;
const FETCH_MAX_REDIRECTS = 3;

/**
 * GET with timeout, https-only manual redirects, capped body.
 * Returns a small Response-like { status, headers, text(), arrayBuffer() }.
 * Throws (caught by callers → pending) on non-https, timeout, over cap.
 */
async function safeFetch(url, init = {}) {
  let current = String(url);
  const chain = [];
  for (let hop = 0; hop <= FETCH_MAX_REDIRECTS; hop++) {
    chain.push(current);
    const u = parseUrl(current);
    if (!u || u.protocol !== "https:") throw new Error("https only");
    const res = await pkFetch(current, {
      method: "GET",
      headers: init.headers || UA,
      redirect: "manual",
      signal: AbortSignal.timeout(FETCH_TIMEOUT_MS),
    });
    if (res.status >= 300 && res.status < 400 && res.headers.get("location")) {
      current = new URL(res.headers.get("location"), current).toString();
      continue;
    }
    const cl = parseInt(res.headers.get("content-length") || "", 10);
    if (Number.isFinite(cl) && cl > FETCH_MAX_BYTES) {
      throw new Error(`body over ${FETCH_MAX_BYTES} bytes`);
    }
    const chunks = [];
    let total = 0;
    if (res.body && res.body.getReader) {
      const reader = res.body.getReader();
      for (;;) {
        const { done, value } = await reader.read();
        if (done) break;
        total += value.byteLength;
        if (total > FETCH_MAX_BYTES) {
          try { await reader.cancel(); } catch {}
          throw new Error(`body over ${FETCH_MAX_BYTES} bytes`);
        }
        chunks.push(value);
      }
    }
    const buf = new Uint8Array(total);
    let off = 0;
    for (const c of chunks) { buf.set(c, off); off += c.byteLength; }
    return {
      status: res.status,
      url: current,
      chain,
      bytes: buf,
      headers: res.headers,
      arrayBuffer: async () => buf.buffer,
      text: async () => new TextDecoder("utf-8", { fatal: false }).decode(buf),
    };
  }
  throw new Error("too many redirects");
}

const SHA256_RE = /^sha256:([0-9a-f]{64})(?:\s+(https:\/\/\S+))?$/i;
const PEERKITH_HOSTS = new Set(["peerkith.com", "www.peerkith.com"]);

/** github.com|gitlab.com|… /commit/<40hex> or /commits/<40hex> (incl. gitlab /-/commit/) */
const GIT_COMMIT_RE =
  /^https:\/\/([^/]+)\/(?:.+?\/)+(?:-\/)?commits?\/([0-9a-f]{40})(?:\/?[?#].*)?$/i;

/** GitHub Actions run or check-runs style */
const CI_RUN_RE =
  /^https:\/\/(?:www\.)?github\.com\/([^/]+)\/([^/]+)\/actions\/runs\/(\d+)(?:\/(?:attempts\/\d+|jobs\/\d+))?(?:\/?[?#].*)?$/i;
const CI_CHECK_RUN_API_RE =
  /^https:\/\/api\.github\.com\/repos\/([^/]+)\/([^/]+)\/check-runs\/(\d+)(?:\/?[?#].*)?$/i;
const CI_CHECK_RUN_HTML_RE =
  /^https:\/\/(?:www\.)?github\.com\/([^/]+)\/([^/]+)\/(?:runs|check-runs)\/(\d+)(?:\/?[?#].*)?$/i;

function isOffOriginHost(hostname) {
  if (!hostname) return false;
  return !PEERKITH_HOSTS.has(String(hostname).toLowerCase());
}

function parseUrl(s) {
  try {
    return new URL(s);
  } catch {
    return null;
  }
}

function contentTypeIsHtml(ct) {
  if (!ct) return false;
  const base = ct.split(";")[0].trim().toLowerCase();
  return base === "text/html";
}

function contentTypeIsJson(ct) {
  if (!ct) return false;
  const base = ct.split(";")[0].trim().toLowerCase();
  return base === "application/json";
}

async function sha256HexBytes(buf) {
  const digest = await crypto.subtle.digest("SHA-256", buf);
  return [...new Uint8Array(digest)]
    .map((b) => b.toString(16).padStart(2, "0"))
    .join("");
}

async function sha256HexString(text) {
  return sha256HexBytes(new TextEncoder().encode(text));
}

function tryParseJsonObject(text) {
  try {
    const v = JSON.parse(text);
    if (v !== null && typeof v === "object" && !Array.isArray(v)) return v;
    return null;
  } catch {
    return null;
  }
}

/**
 * When body is JSON, require body.job === job.trim().
 * @returns {{ ok: true } | { ok: false, detail: string }}
 */
function requireJsonJob(bodyObj, jobCtx) {
  const job =
    typeof jobCtx === "string" && jobCtx.trim() ? jobCtx.trim() : "";
  if (!job) {
    return {
      ok: false,
      detail: "job required for JSON proof body (Proof Bind)",
    };
  }
  if (!("job" in bodyObj) || typeof bodyObj.job !== "string") {
    return {
      ok: false,
      detail: "JSON proof body missing string job (Proof Bind)",
    };
  }
  if (bodyObj.job.trim() !== job) {
    return {
      ok: false,
      detail: "JSON proof body.job !== job (Proof Bind)",
    };
  }
  return { ok: true };
}

function looksSoft404(text, status) {
  if (status === 404) return true;
  if (typeof text !== "string") return false;
  const head = text.slice(0, 4000).toLowerCase();
  // GitHub/GitLab soft-404 HTML pages often still return 200
  if (/page not found|404 not found|this is not the web page you are looking for/.test(head))
    return true;
  if (/<title[^>]*>\s*page not found/i.test(text.slice(0, 2000))) return true;
  if (
    /commit not found|doesn't look like a valid commit|no commit found|couldn['’]t find that commit/i.test(
      head
    )
  )
    return true;
  return false;
}

function htmlLooksLikeSuccess(text) {
  if (typeof text !== "string" || !text) return false;
  const head = text.slice(0, 8000).toLowerCase();
  // Fail closed unless a clear success signal appears
  if (/\bconclusion["']?\s*[:=]\s*["']?success\b/.test(head)) return true;
  if (/\bstatus["']?\s*[:=]\s*["']?success\b/.test(head)) return true;
  if (/aria-label=["'][^"']*\bsuccess(ful)?\b/i.test(text.slice(0, 12000)))
    return true;
  if (/\b(check run|workflow run)\b[^<]{0,80}\bsuccess(ful)?\b/i.test(text.slice(0, 12000)))
    return true;
  // Common GH Actions completed-success badges in HTML
  if (/octicon-check\b[^>]*>[\s\S]{0,200}\bsuccessful\b/i.test(text.slice(0, 20000)))
    return true;
  if (/\bcompleted\b[^<]{0,40}\bsuccessfully\b/i.test(head)) return true;
  return false;
}

/**
 * Sync classify — no fetch.
 * @returns {{ type: string, trusted: boolean }}
 */
function classifyProof(proof) {
  if (typeof proof !== "string" || !proof.trim()) {
    return { type: "unknown", trusted: false };
  }
  const p = proof.trim();

  const sha = p.match(SHA256_RE);
  if (sha) {
    const hex = sha[1];
    if (!/^[0-9a-f]{64}$/i.test(hex)) {
      return { type: "unknown", trusted: false };
    }
    // Bare job-hash is recognized as sha256 but not promote-trusted
    if (!sha[2]) {
      return { type: "sha256", trusted: false };
    }
    return { type: "sha256", trusted: true };
  }
  if (/^sha256:/i.test(p)) {
    return { type: "unknown", trusted: false };
  }

  const u = parseUrl(p);
  if (u && u.protocol === "https:") {
    if (PEERKITH_HOSTS.has(u.hostname.toLowerCase())) {
      // classify label only — never trusted for promote
      return { type: "peerkith", trusted: false };
    }
    if (GIT_COMMIT_RE.test(p)) {
      return { type: "git-commit", trusted: true };
    }
    if (CI_RUN_RE.test(p) || CI_CHECK_RUN_API_RE.test(p) || CI_CHECK_RUN_HTML_RE.test(p)) {
      return { type: "ci", trusted: true };
    }
    return { type: "https-text", trusted: true };
  }

  return { type: "unknown", trusted: false };
}

/**
 * Async verify — eligible for verified queue when ok:true.
 * @param {string} proof
 * @param {{ job?: string }} [ctx]
 * @returns {{ ok: boolean, type: string, trusted: boolean, http_200: boolean|null, world: boolean, detail: string }}
 */
async function verifyProofCore(proof, ctx, fetchT) {
  const classified = classifyProof(proof);
  const base = {
    type: classified.type,
    trusted: classified.trusted,
    http_200: null,
    world: false,
  };
  const jobCtx = ctx && typeof ctx.job === "string" ? ctx.job : "";

  if (typeof proof !== "string" || !proof.trim()) {
    return { ok: false, ...base, detail: "empty proof" };
  }
  const p = proof.trim();

  if (classified.type === "unknown") {
    if (/^https?:\/\//i.test(p)) {
      const u = parseUrl(p);
      if (u && u.protocol === "http:") {
        return {
          ok: false,
          ...base,
          detail: "http not allowed; force https",
        };
      }
    }
    return { ok: false, ...base, detail: "unknown proof type; not trusted" };
  }

  // --- peerkith: NEVER verify (same-origin / own llms) ---
  if (classified.type === "peerkith") {
    const u = parseUrl(p);
    if (!u || u.protocol !== "https:") {
      return { ok: false, ...base, detail: "peerkith proof must be https" };
    }
    try {
      const res = await fetchT(p, { method: "GET", redirect: "follow", headers: UA });
      const http_200 = res.status === 200;
      return {
        ok: false,
        ...base,
        http_200,
        detail: "peerkith same-origin never verifies (Week 1 allowlist)",
      };
    } catch (err) {
      return {
        ok: false,
        ...base,
        http_200: false,
        detail: `peerkith fetch failed: ${err && err.message ? err.message : err}`,
      };
    }
  }

  // --- sha256 ---
  if (classified.type === "sha256") {
    const m = p.match(SHA256_RE);
    const hex = m[1].toLowerCase();
    const url = m[2] || null;

    // Bare sha256:<hex> — commitment only; NEVER verify
    if (!url) {
      return {
        ok: false,
        ...base,
        detail: "bare job-hash is commitment not world evidence; need sha256:<hex> https://…",
      };
    }

    // sha256:<hex> https://… — body hash + optional JSON job bind
    try {
      const res = await fetchT(url, { method: "GET", redirect: "follow", headers: UA });
      const http_200 = res.status === 200;
      if (!http_200) {
        return {
          ok: false,
          ...base,
          http_200: false,
          detail: `sha256 URL GET ${res.status}`,
        };
      }
      const buf = await res.arrayBuffer();
      const got = await sha256HexBytes(buf);
      if (got !== hex) {
        return {
          ok: false,
          ...base,
          http_200: true,
          detail: `sha256 mismatch expected=${hex} got=${got}`,
        };
      }
      const text = new TextDecoder("utf-8", { fatal: false }).decode(buf);
      const asJson = tryParseJsonObject(text);
      if (asJson) {
        const jr = requireJsonJob(asJson, jobCtx);
        if (!jr.ok) {
          return { ok: false, ...base, http_200: true, detail: jr.detail };
        }
        const world = isOffOriginHost(parseUrl(url)?.hostname);
        return {
          ok: true,
          ...base,
          http_200: true,
          world,
          detail: "sha256 body matches; JSON body.job === job",
        };
      }
      {
        const world = isOffOriginHost(parseUrl(url)?.hostname);
        return {
          ok: true,
          ...base,
          http_200: true,
          world,
          detail: "sha256 body matches",
        };
      }
    } catch (err) {
      return {
        ok: false,
        ...base,
        http_200: false,
        detail: `sha256 fetch failed: ${err && err.message ? err.message : err}`,
      };
    }
  }

  // --- git-commit ---
  if (classified.type === "git-commit") {
    const m = p.match(GIT_COMMIT_RE);
    if (!m) {
      return { ok: false, ...base, detail: "git-commit URL parse failed" };
    }
    const host = m[1].toLowerCase();
    const sha = m[2].toLowerCase();
    const u = parseUrl(p);
    if (!u || u.protocol !== "https:") {
      return { ok: false, ...base, detail: "git-commit requires https URL" };
    }

    // Prefer GitHub API when host is github.com
    const ghPath = p.match(
      /^https:\/\/(?:www\.)?github\.com\/([^/]+)\/([^/]+)\/commits?\/([0-9a-f]{40})/i
    );
    if (ghPath) {
      const owner = ghPath[1];
      const repo = ghPath[2];
      const apiUrl = `https://api.github.com/repos/${owner}/${repo}/commits/${sha}`;
      try {
        const res = await fetchT(apiUrl, {
          method: "GET",
          redirect: "follow",
          headers: {
            ...UA,
            Accept: "application/vnd.github+json",
          },
        });
        const http_200 = res.status === 200;
        if (!http_200) {
          return {
            ok: false,
            ...base,
            http_200: false,
            detail: `git-commit API GET ${res.status}`,
          };
        }
        const ct = res.headers.get("content-type") || "";
        const text = await res.text();
        if (contentTypeIsHtml(ct) || looksSoft404(text, res.status)) {
          return {
            ok: false,
            ...base,
            http_200: true,
            detail: "git-commit soft-404 / HTML; fail closed",
          };
        }
        const obj = tryParseJsonObject(text);
        if (!obj) {
          return {
            ok: false,
            ...base,
            http_200: true,
            detail: "git-commit API body not JSON",
          };
        }
        const gotSha = String(obj.sha || obj.commit?.sha || "").toLowerCase();
        if (gotSha !== sha && !gotSha.startsWith(sha.slice(0, 7))) {
          // also accept full sha match in nested
          const blob = JSON.stringify(obj).toLowerCase();
          if (!blob.includes(sha)) {
            return {
              ok: false,
              ...base,
              http_200: true,
              detail: `git-commit SHA not found in API response expected=${sha}`,
            };
          }
        }
        return {
          ok: true,
          ...base,
          http_200: true,
          world: isOffOriginHost(host),
          detail: `git-commit ${sha} resolved via API`,
        };
      } catch (err) {
        return {
          ok: false,
          ...base,
          http_200: false,
          detail: `git-commit API fetch failed: ${err && err.message ? err.message : err}`,
        };
      }
    }

    // Generic: GET page, require SHA present, fail closed on soft-404 HTML
    try {
      const res = await fetchT(p, { method: "GET", redirect: "follow", headers: UA });
      const http_200 = res.status === 200;
      if (!http_200) {
        return {
          ok: false,
          ...base,
          http_200: false,
          detail: `git-commit GET ${res.status}`,
        };
      }
      const text = await res.text();
      if (looksSoft404(text, res.status)) {
        return {
          ok: false,
          ...base,
          http_200: true,
          detail: "git-commit soft-404; fail closed",
        };
      }
      const lower = text.toLowerCase();
      if (!lower.includes(sha)) {
        return {
          ok: false,
          ...base,
          http_200: true,
          detail: `git-commit page missing SHA ${sha}`,
        };
      }
      return {
        ok: true,
        ...base,
        http_200: true,
        world: isOffOriginHost(host),
        detail: `git-commit ${sha} present on page`,
      };
    } catch (err) {
      return {
        ok: false,
        ...base,
        http_200: false,
        detail: `git-commit fetch failed: ${err && err.message ? err.message : err}`,
      };
    }
  }

  // --- ci ---
  if (classified.type === "ci") {
    const u = parseUrl(p);
    if (!u || u.protocol !== "https:") {
      return { ok: false, ...base, detail: "ci requires https URL" };
    }

    const apiCheck = p.match(CI_CHECK_RUN_API_RE);
    const runM = p.match(CI_RUN_RE);
    const htmlCheck = p.match(CI_CHECK_RUN_HTML_RE);

    // Prefer Actions runs API
    if (runM) {
      const owner = runM[1];
      const repo = runM[2];
      const runId = runM[3];
      const apiUrl = `https://api.github.com/repos/${owner}/${repo}/actions/runs/${runId}`;
      try {
        const res = await fetchT(apiUrl, {
          method: "GET",
          redirect: "follow",
          headers: {
            ...UA,
            Accept: "application/vnd.github+json",
          },
        });
        const http_200 = res.status === 200;
        if (!http_200) {
          return {
            ok: false,
            ...base,
            http_200: false,
            detail: `ci Actions API GET ${res.status}`,
          };
        }
        const text = await res.text();
        if (looksSoft404(text, res.status)) {
          return {
            ok: false,
            ...base,
            http_200: true,
            detail: "ci Actions soft-404; fail closed",
          };
        }
        const obj = tryParseJsonObject(text);
        if (!obj) {
          return {
            ok: false,
            ...base,
            http_200: true,
            detail: "ci Actions API body not JSON; fail closed",
          };
        }
        const conclusion = String(obj.conclusion || "").toLowerCase();
        const status = String(obj.status || "").toLowerCase();
        if (conclusion === "success" || (status === "completed" && conclusion === "success")) {
          return {
            ok: true,
            ...base,
            http_200: true,
            world: true,
            detail: `ci Actions run ${runId} conclusion=success`,
          };
        }
        return {
          ok: false,
          ...base,
          http_200: true,
          detail: `ci Actions run not success (status=${status} conclusion=${conclusion || "null"}); fail closed`,
        };
      } catch (err) {
        return {
          ok: false,
          ...base,
          http_200: false,
          detail: `ci Actions fetch failed: ${err && err.message ? err.message : err}`,
        };
      }
    }

    if (apiCheck) {
      try {
        const res = await fetchT(p, {
          method: "GET",
          redirect: "follow",
          headers: {
            ...UA,
            Accept: "application/vnd.github+json",
          },
        });
        const http_200 = res.status === 200;
        if (!http_200) {
          return {
            ok: false,
            ...base,
            http_200: false,
            detail: `ci check-run API GET ${res.status}`,
          };
        }
        const text = await res.text();
        const obj = tryParseJsonObject(text);
        if (!obj) {
          return {
            ok: false,
            ...base,
            http_200: true,
            detail: "ci check-run API body not JSON; fail closed",
          };
        }
        const conclusion = String(obj.conclusion || "").toLowerCase();
        if (conclusion === "success") {
          return {
            ok: true,
            ...base,
            http_200: true,
            world: true,
            detail: "ci check-run conclusion=success",
          };
        }
        return {
          ok: false,
          ...base,
          http_200: true,
          detail: `ci check-run not success (conclusion=${conclusion || "null"}); fail closed`,
        };
      } catch (err) {
        return {
          ok: false,
          ...base,
          http_200: false,
          detail: `ci check-run fetch failed: ${err && err.message ? err.message : err}`,
        };
      }
    }

    // HTML check-runs / runs — require clear success signal
    if (htmlCheck) {
      try {
        const res = await fetchT(p, { method: "GET", redirect: "follow", headers: UA });
        const http_200 = res.status === 200;
        if (!http_200) {
          return {
            ok: false,
            ...base,
            http_200: false,
            detail: `ci HTML GET ${res.status}`,
          };
        }
        const text = await res.text();
        if (looksSoft404(text, res.status)) {
          return {
            ok: false,
            ...base,
            http_200: true,
            detail: "ci HTML soft-404; fail closed",
          };
        }
        if (!htmlLooksLikeSuccess(text)) {
          return {
            ok: false,
            ...base,
            http_200: true,
            detail: "ci HTML success signal ambiguous; fail closed",
          };
        }
        return {
          ok: true,
          ...base,
          http_200: true,
          world: true,
          detail: "ci HTML success signal present",
        };
      } catch (err) {
        return {
          ok: false,
          ...base,
          http_200: false,
          detail: `ci HTML fetch failed: ${err && err.message ? err.message : err}`,
        };
      }
    }

    return { ok: false, ...base, detail: "ci URL not recognized; fail closed" };
  }

  // --- https-text: signed/bound JSON receipt ONLY (off-origin + body.job) ---
  if (classified.type === "https-text") {
    const u = parseUrl(p);
    if (!u || u.protocol !== "https:") {
      return { ok: false, ...base, detail: "https-text requires https URL" };
    }
    if (!isOffOriginHost(u.hostname)) {
      return {
        ok: false,
        ...base,
        detail: "https-text receipt must be off-origin (not peerkith)",
      };
    }
    try {
      const res = await fetchT(p, { method: "GET", redirect: "follow", headers: UA });
      const http_200 = res.status === 200;
      const ct = res.headers.get("content-type") || "";
      if (!http_200) {
        return {
          ok: false,
          ...base,
          http_200: false,
          detail: `https-text GET ${res.status}`,
        };
      }
      if (contentTypeIsHtml(ct)) {
        return {
          ok: false,
          ...base,
          http_200: true,
          detail: "html proof rejected; need application/json receipt with body.job",
        };
      }

      const text = await res.text();
      // Reject HTML-looking bodies even if CT lies
      const trimmed = text.trimStart().slice(0, 64).toLowerCase();
      if (
        trimmed.startsWith("<!doctype") ||
        trimmed.startsWith("<html") ||
        contentTypeIsHtml(ct)
      ) {
        return {
          ok: false,
          ...base,
          http_200: true,
          detail: "HTML-looking body rejected; need JSON receipt",
        };
      }

      const asJson = tryParseJsonObject(text);
      if (!asJson) {
        // Bare URL GET 200 (incl. text/plain) → pending
        return {
          ok: false,
          ...base,
          http_200: true,
          detail:
            "bare URL GET 200 not enough; need JSON receipt with body.job (or sha256/git-commit/ci)",
        };
      }
      if (!contentTypeIsJson(ct) && !asJson) {
        return {
          ok: false,
          ...base,
          http_200: true,
          detail: "content-type not application/json",
        };
      }
      const jr = requireJsonJob(asJson, jobCtx);
      if (!jr.ok) {
        return { ok: false, ...base, http_200: true, detail: jr.detail };
      }
      return {
        ok: true,
        ...base,
        http_200: true,
        world: true,
        detail: "https-text JSON receipt; body.job === job; off-origin",
      };
    } catch (err) {
      return {
        ok: false,
        ...base,
        http_200: false,
        detail: `https-text fetch failed: ${err && err.message ? err.message : err}`,
      };
    }
  }

  return { ok: false, ...base, detail: "unknown proof type; not trusted" };
}

/**
 * Async verify — Week-1 broker result + where the proof lives + job binding.
 * owned: declared proof host OR any redirect hop (incl. final host) is owned.
 * job_bound: JSON body.job === job (checked in core) or exact job text in the
 * fetched artifact (>= JOB_TEXT_MIN chars). Only meaningful when ok:true.
 */
async function verifyProof(proof, ctx = {}) {
  const hops = [];
  let lastBytes = null;
  const fetchT = async (u, init) => {
    const r = await safeFetch(u, init);
    hops.push(...(r.chain || []), r.url);
    lastBytes = r.bytes || null;
    return r;
  };
  const c = ctx || {};
  const v = await verifyProofCore(proof, c, fetchT);
  const p = typeof proof === "string" ? proof.trim() : "";
  const sha = p.match(SHA256_RE);
  const declared = sha ? sha[2] || null : parseUrl(p) ? p : null;
  const hosts = [declared, ...hops]
    .map((u) => (u ? (parseUrl(u)?.hostname || "").toLowerCase() : ""))
    .filter(Boolean);
  const job = typeof c.job === "string" ? c.job.trim() : "";
  let job_bound = false;
  let bound_by = null;
  if (v.ok && lastBytes && job) {
    const text = new TextDecoder("utf-8", { fatal: false }).decode(lastBytes);
    const obj = tryParseJsonObject(text);
    if (obj && typeof obj.job === "string" && obj.job.trim() === job) {
      job_bound = true;
      bound_by = "json-job";
    } else if (job.length >= JOB_TEXT_MIN && text.includes(job)) {
      job_bound = true;
      bound_by = "job-text";
    }
  }
  return {
    ...v,
    job_bound,
    bound_by,
    final_host: hosts.length ? hosts[hosts.length - 1] : null,
    owned: hosts.some(isOwnedHost),
  };
}

// ---- tier.js ----
/**
 * Row tier (Front door). Per row from facts only — no key history, no score.
 * Tiers are LABELS for where/how the proof lives, not a ladder (TL addendum #1).
 * Fixed fail-down order (TL addendum #3):
 *   1. checks fail (broker not ok, or card unsigned / sig invalid) → pending
 *   2. proof not job-bound (no JSON body.job === job, no exact job text) → test
 *   3. proof host owned (OWNED_HOSTS; any redirect hop incl. final)   → self
 *   4. otherwise                                                        → verified
 * Only verified says yes (ok:true). verified_by = plain facts, verified only.
 */



const TIERS = ["verified", "self", "test", "pending"];

function str(v) {
  return typeof v === "string" ? v.trim() : "";
}

/**
 * @param {{card?:string, job?:string, proof?:string}} row
 * @param {{ lazy?: boolean }} [opts] lazy: skip proof fetch when it cannot promote
 * @returns {Promise<{tier:string, verified_by:object|null, reason:string,
 *   checked_at:string, broker:string, v:object|null, identity:object|null}>}
 */
async function checkRow(row, opts = {}) {
  const card = str(row && row.card);
  const job = str(row && row.job);
  const proofRaw = str(row && row.proof);
  const checked_at = new Date().toISOString();
  const out = (tier, reason, verified_by = null, v = null, identity = null) => ({
    tier,
    verified_by,
    reason,
    checked_at,
    broker: BROKER_VERSION,
    v,
    identity,
  });

  if (!proofRaw) return out("pending", "missing proof");
  if (!card || !job) return out("pending", "need card+job for full check");

  const identity = await checkIdentityForPromote(card, job, proofRaw);
  const { proof: proofCore } = stripSigAddon(proofRaw);
  const cls = classifyProof(proofCore);

  let v;
  const skip = (detail) => ({
    ok: false, type: cls.type, trusted: cls.trusted, http_200: null, world: false, detail,
  });
  if (opts.lazy && cls.type === "peerkith") {
    // Never verifies; skip the same-origin fetch.
    v = skip("peerkith same-origin never verifies (Week 1 allowlist)");
  } else if (opts.lazy && cls.trusted && !identity.promote) {
    v = skip("proof not fetched (identity failed first)");
  } else {
    // Untrusted non-peerkith types return without any fetch.
    v = await verifyProof(proofCore, { job });
  }

  const reasons = [];
  if (!v.ok) reasons.push(v.detail || `proof not verified (${v.type})`);
  if (!identity.promote) reasons.push(identity.detail);
  if (reasons.length) return out("pending", reasons.join("; "), null, v, identity);

  if (v.job_bound !== true) {
    return out("test", `proof not job-bound; ${v.detail}`, null, v, identity);
  }
  if (v.owned === true) {
    return out("self", `proof host owned (${v.final_host || "owned"}); ${v.detail}`, null, v, identity);
  }
  return out(
    "verified",
    `${v.detail}; job-bound (${v.bound_by}); ${identity.detail}`,
    { proof: v.type, identity: "signed", bound: v.bound_by, world: true, broker: BROKER_VERSION },
    v,
    identity
  );
}

/** Stored verdict (KV wall:tiers[id]) — no broker internals. */
function storedVerdict(c) {
  return {
    tier: c.tier,
    verified_by: c.verified_by,
    reason: c.reason,
    checked_at: c.checked_at,
    broker: c.broker,
  };
}

// ---- CLI / exports ----
async function rowId(r) {
  const canonical = JSON.stringify({ card: r.card, job: r.job, proof: r.proof, incident: r.incident, cap: r.cap });
  const d = await crypto.subtle.digest("SHA-256", new TextEncoder().encode(canonical));
  return [...new Uint8Array(d)].map((b) => b.toString(16).padStart(2, "0")).join("");
}

async function verifyRow(r) {
  const s = (k) => (typeof r[k] === "string" ? r[k].trim() : "");
  const c = await checkRow({ card: s("card"), job: s("job"), proof: s("proof") }, { lazy: true });
  const out = {
    ok: c.tier === "verified",
    tier: c.tier,
    reason: c.reason,
    verified_by: c.verified_by,
    checked_at: c.checked_at,
    broker: c.broker,
  };
  if (["card", "job", "proof", "incident", "cap"].every((k) => typeof r[k] === "string")) {
    out.row = await rowId(r);
  }
  return out;
}

function useOffline(bytes) {
  pkFetch = async () => {
    const text = new TextDecoder().decode(bytes);
    let ct = "application/octet-stream";
    try { JSON.parse(text); ct = "application/json"; } catch {}
    return new Response(bytes, { status: 200, headers: { "content-type": ct } });
  };
}

const api = { BROKER_VERSION, OWNED_HOSTS, isOwnedHost, checkRow, verifyRow, classifyProof, verifyProof, checkIdentityForPromote, useOffline };

async function main(argv) {
  const fs = process.getBuiltinModule("node:fs");
  const opt = {};
  for (let i = 0; i < argv.length; i++) {
    if (argv[i].startsWith("--")) opt[argv[i].slice(2)] = argv[i + 1] && !argv[i + 1].startsWith("--") ? argv[++i] : true;
  }
  if (opt.version) { console.log(BROKER_VERSION); return 0; }
  let row = { card: opt.card, job: opt.job, proof: opt.proof };
  if (typeof opt.row === "string") {
    const src = opt.row.trim().startsWith("{") ? opt.row : fs.readFileSync(opt.row, "utf8");
    row = JSON.parse(src);
  }
  if (typeof opt.offline === "string") useOffline(new Uint8Array(fs.readFileSync(opt.offline)));
  const out = await verifyRow(row);
  console.log(JSON.stringify(out));
  return out.ok ? 0 : 1;
}

if (typeof module !== "undefined" && module.exports) module.exports = api;
else if (typeof globalThis !== "undefined") globalThis.peerkithVerify = api;

const isCli =
  typeof process !== "undefined" && process.argv &&
  (typeof module !== "undefined" && typeof require !== "undefined"
    ? require.main === module
    : /verify(-ref)?.c?js$/.test(process.argv[1] || ""));
if (isCli) {
  main(process.argv.slice(2)).then((code) => process.exit(code), (e) => { console.error(String(e && e.stack || e)); process.exit(2); });
}
})();
